version: '3.9'
services:
  postgres:
    image: 'postgres'
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
  pgadmin:
    image: 'dpage/pgadmin4'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - '80:80'
